<?php
/**
 * SearchWiz React Loader
 *
 * Enqueues the React bundle (built by npm run build)
 * and passes WordPress config to React via wp_localize_script
 *
 * @package SearchWiz
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class SearchWiz_React_Loader {

    /**
     * Initialize hooks
     */
    public static function init() {
        add_action( 'wp_enqueue_scripts', array( __CLASS__, 'enqueue_scripts' ) );
    }

    /**
     * Enqueue React bundle
     * This runs after npm run build creates public/dist/index.js
     */
    public static function enqueue_scripts() {

        // Check if React is enabled in admin settings
        $enable_react = get_option( 'searchwiz_enable_react', true );
        if ( !$enable_react ) {
            echo '<!-- [SearchWiz] React disabled in settings -->';
            return;
        }

        // Only load React on SearchWiz search pages (/sw) or when explicitly enabled
        $is_searchwiz_search = get_query_var( 'is_searchwiz_search' );

        if ( is_search() && !$is_searchwiz_search ) {
            // This is a regular WordPress search (/?s=), check if SearchWiz should load
            $sw_settings = get_option( 'searchwiz_settings', array() );
            $use_searchwiz_default = ! isset( $sw_settings['default_search'] ) || 1 === (int) $sw_settings['default_search'];

            if ( !$use_searchwiz_default ) {
                echo '<!-- [SearchWiz] Regular search (/?s=) and checkbox unchecked, not loading React -->';
                return;
            }
        }

        // Check if theme integration checkbox is unchecked for supported themes
        if ( is_search() && !$is_searchwiz_search && class_exists( 'SearchWiz_Theme_Integration' ) ) {
            $theme_integration = new SearchWiz_Theme_Integration();
            $is_supported = $theme_integration->is_theme_supported();

            if ( $is_supported ) {
                // Theme is supported - check if integration is enabled
                $theme_integration_option = get_option( 'searchwiz_theme_integration', array( 'enabled' => 'on' ) );
                $theme_integration_enabled = ! isset( $theme_integration_option['enabled'] ) || 'on' === $theme_integration_option['enabled'];

                if ( !$theme_integration_enabled ) {
                    echo '<!-- [SearchWiz] Supported theme but integration disabled, not loading on search results page -->';
                    return;
                }
            }
        }

        // Path to built React bundle
        $dist_path = dirname( __FILE__ ) . '/dist/index.js';
        $asset_path = dirname( __FILE__ ) . '/dist/index.asset.php';

        // Check if bundle exists (npm run build was executed)
        if ( !file_exists( $dist_path ) ) {
            echo '<!-- [SearchWiz] Bundle NOT FOUND at: ' . esc_html($dist_path) . ' -->';
            return;
        }
        echo '<!-- [SearchWiz] Bundle found! Enqueueing React from: ' . esc_html($dist_path) . ' -->';

        // Load asset file (auto-generated by wp-scripts with correct dependencies)
        $asset_file = file_exists( $asset_path ) ? require( $asset_path ) : array(
            'dependencies' => array( 'wp-element' ),
            'version' => filemtime( $dist_path ),
        );

        // Get the plugin URL for enqueuing
        $plugin_url = plugins_url( '/', SEARCHWIZ_PLUGIN_FILE );
        $dist_url = $plugin_url . 'public/dist/index.js';
        $style_url = $plugin_url . 'public/dist/index.css';

        echo '<!-- [SearchWiz] Script URL: ' . esc_html($dist_url) . ' -->';
        echo '<!-- [SearchWiz] Dependencies: ' . esc_html(implode(', ', $asset_file['dependencies'])) . ' -->';

        // Register and enqueue React bundle with proper dependencies from asset file
        wp_register_script(
            'searchwiz-react',
            $dist_url,
            $asset_file['dependencies'], // Use dependencies from asset file
            $asset_file['version'],
            true // Load in footer
        );

        wp_enqueue_script( 'searchwiz-react' );
        echo '<!-- [SearchWiz] React script enqueued successfully! -->';
        echo '<!-- [SearchWiz] Load in footer: true -->';

        // Enqueue AJAX search CSS (required for result styling)
        $min = ( defined( 'SW_DEBUG' ) && SW_DEBUG ? '' : '.min' );
        wp_enqueue_style(
            'searchwiz-ajax-search-styles',
            $plugin_url . 'public/css/searchwiz-ajax-search' . $min . '.css',
            array(),
            SEARCHWIZ_VERSION
        );

        // Enqueue React bundle styles if they exist
        $style_path = dirname( __FILE__ ) . '/dist/index.css';
        if ( file_exists( $style_path ) ) {
            wp_enqueue_style(
                'searchwiz-react-style',
                $style_url,
                array( 'searchwiz-ajax-search-styles' ), // Load after AJAX CSS
                filemtime( $style_path )
            );
        }

        // Get search query from current page
        // Also check for isSearchpage parameter for dedicated search page
        $search_query = '';
        $is_search_page = is_search() || isset( $_GET['isSearchpage'] );

        if ( is_search() ) {
            $search_query = get_search_query();
        } elseif ( isset( $_GET['s'] ) ) {
            $search_query = sanitize_text_field( $_GET['s'] );
        }
        // Get console logs so we can see what is happening.
        // Create debug wrapper - only enabled if ?searchwiz_admin_debug=1 in URL or admin setting
        $debug_enabled = isset( $_GET['searchwiz_debug'] ) || get_option( 'searchwiz_debug_mode', false );
        $debug_js = $debug_enabled ? 'true' : 'false';

        $inline_script = 'window.searchwizDebug = {' .
            'enabled: ' . $debug_js . ',' .
            'log: function(msg, data) {' .
              'if (this.enabled) {' .
                'console.log(\'[SearchWiz] \' + msg, data !== undefined ? data : \'\');' .
              '}' .
            '}' .
          '};' .
          'function ensureReactMount() {' .
            'if (!document.getElementById(\'searchwiz-react-results\')) {' .
              'var reactContainer = document.createElement(\'div\');' .
              'reactContainer.id = \'searchwiz-react-results\';' .
              'var urlParams = new URLSearchParams(window.location.search);' .
              'var isSearchPage = urlParams.get(\'isSearchpage\') === \'true\' || urlParams.has(\'s\');' .
              'if (isSearchPage) {' .
                'reactContainer.style.cssText = \'position: relative !important; width: 100%; max-width: 1200px; margin: 20px auto; padding: 0; display: block; background: white; min-height: 400px;\';' .
                'var contentArea = document.querySelector(\'.site-main, main, #main, #content, .content-area, article\');' .
                'if (contentArea) {' .
                  'var searchResults = contentArea.querySelectorAll(\'article, .hentry, .search-entry, .post, .page\');' .
                  'searchResults.forEach(function(el) {' .
                    'el.style.display = \'none\';' .
                  '});' .
                  'var headings = contentArea.querySelectorAll(\'h1, .page-title, .entry-title, .search-title\');' .
                  'headings.forEach(function(heading) {' .
                    'var text = heading.textContent.toLowerCase();' .
                    'if (text.indexOf(\'search\') !== -1 || text.indexOf(\'result\') !== -1) {' .
                      'heading.style.display = \'none\';' .
                    '}' .
                  '});' .
                  'contentArea.insertBefore(reactContainer, contentArea.firstChild);' .
                '} else {' .
                  'var header = document.querySelector(\'header, .site-header\');' .
                  'if (header && header.nextSibling) {' .
                    'header.parentNode.insertBefore(reactContainer, header.nextSibling);' .
                  '} else {' .
                    'document.body.appendChild(reactContainer);' .
                  '}' .
                '}' .
              '} else {' .
                'reactContainer.style.cssText = \'position: relative !important; z-index: 9999; background: white; box-shadow: 0 2px 10px rgba(0,0,0,0.1); border-radius: 4px; width: 100%; max-width: 600px; margin-top: 10px; display: none;\';' .
                'document.body.appendChild(reactContainer);' .
              '}' .
            '}' .
          '}' .
          'if (document.readyState === \'loading\') {' .
            'document.addEventListener(\'DOMContentLoaded\', ensureReactMount);' .
          '} else {' .
            'ensureReactMount();' .
          '}';

        wp_add_inline_script('searchwiz-react', $inline_script, 'before');
        // Pass WordPress config to React
        $display_settings = get_option( 'searchwiz_display_settings', array() );

        wp_localize_script( 'searchwiz-react', 'searchwiz', array(
            'ajax_url'  => admin_url( 'admin-ajax.php' ),
            'nonce'     => wp_create_nonce( 'searchwiz_nonce' ),
            'query'     => $search_query,
            'form_id'   => 0,
            'config'    => array(
                'layout'             => isset( $display_settings['layout'] ) ? $display_settings['layout'] : 'grid',
                'per_page'           => isset( $display_settings['per_page'] ) ? $display_settings['per_page'] : 10,
                'show_thumbnails'    => isset( $display_settings['show_thumbnails'] ) ? $display_settings['show_thumbnails'] : 1,
                'show_excerpts'      => isset( $display_settings['show_excerpts'] ) ? $display_settings['show_excerpts'] : 1,
                'excerpt_length'     => isset( $display_settings['excerpt_length'] ) ? $display_settings['excerpt_length'] : 20,
                'primary_color'      => isset( $display_settings['primary_color'] ) ? $display_settings['primary_color'] : '#0073aa',
                'title_font_size'    => isset( $display_settings['title_font_size'] ) ? $display_settings['title_font_size'] : '18',
                'card_spacing'       => isset( $display_settings['card_spacing'] ) ? $display_settings['card_spacing'] : '15',
                'card_border_radius' => isset( $display_settings['card_border_radius'] ) ? $display_settings['card_border_radius'] : '4',
                'highlight_terms'    => isset( $display_settings['highlight_terms'] ) ? $display_settings['highlight_terms'] : 1,
            ),
        ) );
    }
}

// Initialize when class is loaded
SearchWiz_React_Loader::init();